#!/bin/bash
set -euo pipefail

# Sync a list of files and directories from an input file to another location

filelist=$2
backupdest=$3


if [[ "$#" -eq 0 ]]; then
  ${0} help
elif [[ "$1" == "help" ]]; then
  echo "usage: $(basename ${0}) sync <file with list of files and dirs to backup> <destination dir>"
elif [[ "$1" == "sync" ]]; then

  if [ ! -d "${backupdest}" ]; then
    echo "Backup destination ${backupdest} does not exist"
    exit 1
  fi

  exec 200>/tmp/$(basename ${0}).lock
  flock -n 200 || { echo "error: sync is still in progress" >&2; exit 1; }

  while IFS= read -r srcitem; do

  if [ -d "${srcitem}" ]; then
    rsync --archive --relative --delete \
      --exclude={.env/,.venv/,venv/} \
      "${srcitem%/}" "${backupdest}"
  elif [ -f "${srcitem}" ]; then
    rsync --archive --relative "${srcitem}" "${backupdest}"
  fi
  
  done < "${filelist}"

else
  echo "unknown command: $@" >&2
  exit 1
fi
